import '@/global/styles/index.scss';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

import AppProviders from '@/global/providers/AppProviders/ui/AppProviders';
import { PageParams } from '@/shared/types/pageParams';
import { HStack } from '@/shared/ui/Stack';
import { Navbar } from '@/widgets/Navbar';
import { Sidebar } from '@/widgets/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: PageParams;
}

export default function RootLayout({ children, params }: RootLayoutProps) {
    const cookieStore = cookies();
    const themeCookie = cookieStore.get('theme')?.value ?? 'auto';

    return (
        <html lang={params.lang} data-theme={themeCookie}>
            <body className={`app`}>
                <Navbar themeCookie={themeCookie} lang={params.lang} />
                <HStack>
                    <Sidebar lang={params.lang} />
                    <AppProviders>{children}</AppProviders>
                </HStack>
            </body>
        </html>
    );
}
