import '@/global/styles/index.scss';

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { cookies } from 'next/headers';

import AppProviders from '@/global/providers/AppProviders/ui/AppProviders';
import { PageParams } from '@/shared/types/pageParams';
import { Footer } from '@/shared/ui/Footer';
import { HStack } from '@/shared/ui/Stack';
import { Navbar } from '@/widgets/Navbar';
import { Sidebar } from '@/widgets/Sidebar';

const montserrat = Montserrat({
    weight: ['300', '400', '500', '600'],
    subsets: ['latin'],
    display: 'swap',
    fallback: ['Arial', 'sans-serif'],
    variable: '--font-montserrat',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: PageParams;
}

export default function RootLayout({ children, params }: RootLayoutProps) {
    const cookieStore = cookies();
    const themeCookie = cookieStore.get('theme')?.value ?? 'auto';

    return (
        <html
            lang={params.lang}
            className={`${montserrat.variable}`}
            data-theme={themeCookie}
        >
            <body className={`app`}>
                <Navbar themeCookie={themeCookie} lang={params.lang} />
                <HStack>
                    <Sidebar lang={params.lang} />
                    <AppProviders>{children}</AppProviders>
                </HStack>
                <Footer lang={params.lang} />
            </body>
        </html>
    );
}
