import '@/global/styles/index.scss';
import '@/shared/config/i18n/i18n';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AppProviders from '@/global/providers/AppProviders/ui/AppProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`app`}>
                <AppProviders>{children}</AppProviders>
            </body>
        </html>
    );
}
